
name: Sync Fork

on:
  workflow_dispatch: # on button click
  # schedule: # should only be active if we pull changes automatically
  #   - cron: '0 8 * * 1' # every monday at 8

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      # - name: Sync-Fork-action
      #   uses: XueMoMo/Sync-Fork-action@v1.0.6
      #   with:
      #     upstream_repository: nrednav/youtube-playlist-duration-calculator
      #     upstream_branch: master
      #     target_branch: master
      #     git_pull_args: --ff-only 
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build script
        run: |
          ./build.sh
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add tampermonkey-script.user.js
          git commit -m "Update script" || echo "Nothing to commit"
          git push