
name: Sync Fork

on:
  # schedule: # should only be active if we pull changes automatically
  #   - cron: '0 8 * * 1' # every monday at 8
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      # - name: Sync-Fork-action
      #   uses: XueMoMo/Sync-Fork-action@v1.0.6
      #   with:
      #     upstream_repository: nrednav/youtube-playlist-duration-calculator
      #     upstream_branch: master
      #     target_branch: master
      #     git_pull_args: --ff-only 
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build script
        run: |
          ./build.sh
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Update script'
          add: 'tampermonkey-script.user.js --force'